---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: default
spec:
  encryptedData:
    PASS: AgA1AEcDonp3kR4heYsz9KU/gr/WxHPDwUvPwRA4C7oXjqem9zJT9rmP2ydZEMtdxpgu3nzIcLx9vvx4inP84WXYY6XUIVVeAy9RLfwcoDkx8EYxavI7k8BixsTm5LWwVLqjazBrUPVjtFny5LuXQzUM12d7ZG5xKBKgnL002bgTlI0ILtOfsJB4icyywIZewgMiZhiKoSS+7Y5o2V18Rau/6dWXGYgoe/ysm2cRFz1OhlhxdnK2IkX2L2r/oBhM/pTANjO7TMVi+nO6wr5RD+2N30e9SJCr0KqQ8KOJnUsjdHgCMnYkPuScHslYwQrOBj4uMmosjzl+jKSQpbr2zBDtOc2QPanpXxUKz2bkQH0wVnXjgn+sUxN7oUoLSWJ87yOdTsdnEZolowb5/r9csfjz7sEK/tXP4WKPElyYrsKacifLmRi1ONTJ7UMvDjmdGfU2Yh6F267gabcQqUURsYUPMWCk3hhuOg0+Zo8M+nnqqcwsbl2qstZbvoQXUoKtm3yxVxmNgGqEO9m6IwuRxYTKtycdggKVmfItk1owf1WLBvM2Mlusf6G/UZNg1Wg3ndnu2XF3tO5aS36Td5fJWbpu4EM8KHmIrmnZ+BcduVCURlGpkbZUiS8mg8V+mAClzApV0P3roCL/SKMSFdcwssZEzG6n75i/tW1p7BVSeeWO1wdPIqt1ZygN+kP+ymMNUurpHwkyL2c=
    USER: AgA3iVFAl10lMdreHcGXrSaD6fFtVD7xg4qm9BdUL278gnDrMVwh6gGhKPbJF2fo4EDPiF8iK/wuyXBlzmz5JqJcUl4u/en4DTbPVlPraz+aW+H7ugv04XcsxR2I5qGtqPH/yMxp1MZmAPzmeWCHRED7nBXINam9cfCvh9MUNhudtsVppRzbOCS2yBj60s0GwPIySdTVBZmkcamBwZbJz9DUZLHNdsmT4xgcAG/MoO5ID5DZlYLoHtZh37LbsEYqsygCB68DMZycessWGuwsaHeVDWgDTX3wCQLyt8bPi1MVzq+obcntRA1N8n1w9FsUBT9q8b5X/L1Janjo+fEtPk1j6ExdYx3x7gkfXI4Q9QYDJTJWR3fCrbETOvbJFgA3d/x0wB2P7epmb/BZNvosf+bpQizwIwaXDKyOwQ7MbWy+wHOu3QP/Kg0jO1jG6nA9/kok3L+R+tZXvvWUx6VJYWXbUHrhU9ZKzfZ7kHfPE3ZZLQM+CZoaHIkq5AzuFjmXKx7I352uRTFZVNl2ZqT96zyBnGdf90WDtbdGc8sVYngYRnaithkZDVHK0tuzTSBbEVK08jIJgPnUhS1SS3ctmNRkBcVMTAnWU66/viMiQNCN0i/sSxb6HasMseZffvLDrydsVV5KdQ6jPd4qICV4H/zzHKr8XaYmcnMAZjqOhiw7houFp5j+N8HcLGB+g8cbKmon1UbX/g==
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: default
