---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: default
spec:
  encryptedData:
    PASS: AgCYEJMCYy4uUFMMtbDlkdgv6coXRDmqJvkC6+WeXN2eDc5u8JbOQ4MApDz+cLkTQs3pxf0x7sLS6C5lUgptXGyFMlV+m9p5hKg3IIc++y97sA/OZjky7qV6llyII1QYu5nczzYAq+55lOOUdKpmmixP9geWrBzI77P5VTYJk7XsJs2536ctXNhf3xZ+OoPfZ+OW95w+4cYcpO0dMmuoMD9hEt5/utkJDgiCDhAn6ln61MDKioqyKV7UqqTS49X4UDwND6vcEn6EwPEpK6MMn5UAhaiz5ZDQ4UjQt4X9+HDou6v/sXoLsQfF9mr2m2wFVp3n7rqE+6orTagbhlfoegKr4FIIGFY87x0kT19w6rn4GrQPIJbc+DROfbRjc7FLvqa2R7b1QgzZHQS40pOfg2gkDnAb0DQGt6EhEVoDh1KgfS/TKVUge2aw5RwV3PbWwrG3v2yIPsRKKdMQ75i/qoEmeTxha9tVd4QWBNi/L+bTWBEICNyBF3ZecNVw0To+RYDqAACbNaa77LTlBGclhk+U5i9st/cCkljuQgQxJtJok7SN3RuW2GczC90/e0Rx3j8+C9y1dJ1SIXj+Zp3DSPDRoCk/PZ115ccKe9apXg9bZXIwa+slzAVcKUAUhR4a1wN1KLcKyvk943ftRPEAC/PPbYvcGA5P6O0zKWrNSjBaKRmOd/us2cxzgyzKc0weXN7BtBeoRuGxELKaWQ==
    USER: AgAYUncyxXB97yio23Se9kb1SjdKicoXo1oFpovrS2MXer35Epdb4tXuPu+vZRu3t6qTYM7IHe65Oz0KJjZbJUIl3kZBzeraAsZBXVTqAbTaE3oOkoy+0eoICpllWfdWBbPNGGdgHyxp5YnryKb+bloXNx0md54bVFHBRCLXjTXYG/1pRMva/EVOAuRGOvykpGCZJwGng9gpXUyLSJd9aLJhDNHuxsbrZnJAdX2308mSBq2EUtfkVIUjwF9uOxiOCiRnb73fs3EtN4z1iFvqpGocN+frAuEsud1saACT+0ZiYK4ziwEIW0NqCIBH47g9KiGJf0qWXXsAgrtxE5u8ObDevd6cVAu3X0N3paZwEKNHo6cZs8UsjlXDM4NaTUp1U86jBT+MXAX/qhJxMZV1Rg78UQgD7Aw5eWbd1F+n7pwAJLhccYyuU3kvK7FdsIxeY+KWFv0ZmD2fad/XfT2RoQFrtvNgSGry9I2/XOtaN7YNsrlMnn06RmbNZbwlZOT9U3pmVQZ2zZR2GsICV/3WHLqhydcb8hUtabiOjRDEsajXmOmF2+69qcN0qLO5zUYUcK19Hn8Bbtj7VmgSPt2H0WkkRpk2mTRTIZ1LrryHXSYkfNiWqnjYoT82iDMQmkF9jjJ/vC7gyGaXSDryr5mHAqm4JhsOhtHAPWj4wow3TCmInQx/b8Hwq1S/lAfVgh8wW1VIMtaFh/5v6IT/MA==
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: default
