version: '3.8'

services:
  github-actions-app:
    image: tommannson/github-actions-app:0.1.2
    container_name: github-actions-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
