name: Build and Push Docker Image

on:
  push:
    tags:
      - "v*.*.*"

env:
  REGISTRY: docker.io
  IMAGE_NAME: tommannson/github-actions-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build project (without tests)
        run: |
          echo "Building project without running tests..."
          ./gradlew build -x test
          echo "✅ Project built successfully!"

      - name: Debug secrets
        run: |
          echo "Checking if secrets are available..."
          if [ -n "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
            echo "✅ DOCKERHUB_USERNAME is set (length: ${#DOCKERHUB_USERNAME})"
          else
            echo "❌ DOCKERHUB_USERNAME is NOT set"
          fi
          if [ -n "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "✅ DOCKERHUB_TOKEN is set (length: ${#DOCKERHUB_TOKEN})"
          else
            echo "❌ DOCKERHUB_TOKEN is NOT set"
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image with JIB
        run: |
          echo "Building multi-platform Docker image with JIB..."

          # Set Docker Hub credentials for JIB
          export DOCKER_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}"
          export DOCKER_PASSWORD="${{ secrets.DOCKERHUB_TOKEN }}"

          # Build and push using JIB (uses version from build.gradle)
          ./gradlew jib \
            -Djib.to.auth.username=$DOCKER_USERNAME \
            -Djib.to.auth.password=$DOCKER_PASSWORD

          echo "✅ Multi-platform Docker image built and pushed successfully!"

      - name: Show image info
        run: |
          echo "📦 Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          echo "🏷️  Tags: Using current version from build.gradle + latest"
          echo "🖥️  Platforms: amd64/linux, arm64/linux, amd64/darwin, arm64/darwin"

      - name: Summary
        run: |
          echo "🎉 Docker image build and push completed successfully!"
          echo "📦 Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          echo "🏷️  Tags: Version from build.gradle + latest"
          echo "🖥️  Multi-platform support: Linux (amd64/arm64) + macOS (amd64/arm64)"
          echo "🚀 Image is now available on Docker Hub!"
