name: New Version Patch

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # Job for Patch version increment
  New_Version_Patch:
    uses: ./.github/workflows/version-bump.yml
    with:
      version-type: patch
    secrets:
      ACCESS_TOKEN: ${{ secrets.MY_PAT }}
